import Workshop1 from '../assets/workshop/workshop1.png';
import Workshop2 from '../assets/workshop/workshop2.png';
import Workshop3 from '../assets/workshop/workshop3.png';

export const categories = ['All', 'Content', 'Design', 'Digital Currencies', 'Growth & Marketing', 'No Code', 'Other'];
export const worshops = [
    {
        seats: '15 seats left',
        image: Workshop1,
        name: 'Mohit Ahuja',
        designation: 'Ex – Zomato, Curefit, RadYes',
        date: '05/12/2021',
        title: 'Sales Workshop',
        oldPrice: '₹1999',
        newPrice: '₹499',
        stars: '9.0',
        students: '120',
        link: '/',
        category: 'Other',
    },{
        seats: '15 seats left',
        image: Workshop2,
        name: 'Saptarshi Prakash ',
        designation: 'Sr. Product Design Manager at Swiggy',
        date: '11/12/2021',
        title: 'UI Kickstarter Workshop',
        oldPrice: '₹1999',
        newPrice: '₹499',
        stars: '9.2',
        students: '5800',
        link: '/',
        category: 'Design',
    },{
        seats: 'Sold Out',
        image: Workshop3,
        name: 'Digital Pratik',
        designation: 'Contextual Content Creator',
        date: '',
        title: 'Content Machine Workshop',
        oldPrice: '₹1999',
        newPrice: '₹499',
        stars: '9.1',
        students: '900',
        link: '/',
        category: 'Content',
    },{
        seats: '11 seats left',
        image: Workshop1,
        name: 'Mohit Ahuja',
        designation: 'Ex – Zomato, Curefit, RadYes',
        date: '04/12/2021',
        title: 'Sales Workshop',
        oldPrice: '₹1999',
        newPrice: '₹499',
        stars: '9.0',
        students: '120',
        link: '/',
        category: 'Growth & Marketing',
    },{
        seats: 'Sold Out',
        image: Workshop2,
        name: 'Anuj Gosalia',
        designation: 'Co-founder & CEO – Terribly Tiny Tales',
        date: '',
        title: 'Content Writing Freelancing',
        oldPrice: '₹1999',
        newPrice: '₹499',
        stars: '9.3',
        students: '1100',
        link: '/',
        category: 'Content',
    },{
        seats: '20 seats left',
        image: Workshop3,
        name: 'Ajeet Khurana',
        designation: 'Former CEO, Zebpay, Angel Investor',
        date: '20/12/2021',
        title: 'Cryptocurrency Kickstarter Workshop',
        oldPrice: '₹1999',
        newPrice: '₹499',
        stars: '9.4',
        students: '2800',
        link: '/',
        category: 'Digital Currencies',
    },{
        seats: '20 seats left',
        image: Workshop1,
        name: 'Keshav & Mayank',
        designation: 'Founders of India’s 1st No-Code Studio',
        date: '20/12/2021',
        title: 'No-Code Kickstarter Workshop',
        oldPrice: '₹1999',
        newPrice: '₹499',
        stars: '9.3',
        students: '5300',
        link: '/',
        category: 'No Code',
    },{
        seats: '10 seats left',
        image: Workshop1,
        name: 'Deepan & Aswini ',
        designation: 'Director – Digital at Webenza | Marketing Measurement Specialist at HSBC',
        date: '12/12/2021',
        title: 'Performance Marketing Workshop',
        oldPrice: '₹1999',
        newPrice: '₹499',
        stars: '9.4',
        students: '3200',
        link: '/',
        category: 'Growth & Marketing',
    }
];